version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: communityvoting-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: communityvoting
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: communityvoting-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: communityvoting-azurite
    restart: always
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --location /data"
    ports:
      - "10000:10000" # Blob Storage
      - "10001:10001" # Queue Storage
      - "10002:10002" # Table Storage
    volumes:
      - azurite_data:/data

volumes:
  postgres_data:
  pgadmin_data:
  azurite_data:
